[package]
org = "isururuhunage"
name = "audio_to_text_summarization_using_openai"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "openai.audio"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "openai.text"
version = "0.1.0"
repository = "local"
