[package]
org = "ai_samples"
name = "slackbot_using_azure_openai"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "azure_openai.chat"
version = "0.1.0"
repository = "local"
